version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "AnyLogicDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d